services:
  adguard:
    container_name: adguardhome
    image: adguard/adguardhome:latest
    restart: unless-stopped
    network_mode: host
    env_file:
      - .env
    volumes:
      - /docker/appdata/adguardhome:/opt/adguardhome/conf
      - /etc/localtime:/etc/localtime:ro
      - /etc/ssl/certs/adguard.crt:/etc/ssl/certs/adguard.crt:ro
      - /etc/ssl/private/adguard.key:/etc/ssl/private/adguard.key:ro
