- name: Create env file for OVH Caddy
  copy:
    dest: /etc/caddy/ovh.env
    owner: caddy
    group: caddy
    mode: '0600'
    content: |
      OVH_ENDPOINT={{ ovh_endpoint }}
      OVH_APPLICATION_KEY={{ ovh_application_key }}
      OVH_APPLICATION_SECRET={{ ovh_application_secret }}
      OVH_CONSUMER_KEY={{ ovh_consumer_key }}

- name: Create systemd override directory for caddy
  file:
    path: /etc/systemd/system/caddy.service.d
    state: directory
    mode: '0755'

- name: Configure EnvironmentFile for Caddy
  copy:
    dest: /etc/systemd/system/caddy.service.d/env.conf
    mode: '0644'
    content: |
      [Service]
      EnvironmentFile=/etc/caddy/ovh.env

- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Restart Caddy
  service:
    name: caddy
    state: restarted