- name: Create env file for OVH Caddy
  copy:
    dest: /etc/caddy/ovh.env
    owner: caddy
    group: caddy
    mode: '0600'
    content: |
      OVH_ENDPOINT={{ OVH_ENDPOINT }}
      OVH_APPLICATION_KEY={{ OVH_APPLICATION_KEY }}
      OVH_APPLICATION_SECRET={{ OVH_APPLICATION_SECRET }}
      OVH_CONSUMER_KEY={{ OVH_CONSUMER_KEY }}

- name: Create systemd override directory for caddy
  file:
    path: /etc/systemd/system/caddy.service.d
    state: directory
    mode: '0755'

- name: Configure EnvironmentFile for Caddy
  copy:
    dest: /etc/systemd/system/caddy.service.d/env.conf
    mode: '0644'
    content: |
      [Service]
      EnvironmentFile=/etc/caddy/ovh.env

- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Copy Caddyfile from repo to server
  copy:
    src: ../../../caddy/Caddyfile
    dest: /etc/caddy/Caddyfile
    owner: caddy
    group: caddy
    mode: '0644'
    backup: yes
  notify: Validate and reload Caddy

- name: Restart Caddy
  service:
    name: caddy
    state: restarted