---
- name: Ensure prerequisites for Caddy repo are present
  apt:
    name:
      - apt-transport-https
      - curl
      - gnupg
      - debian-archive-keyring
      - debian-keyring
    state: present
    update_cache: yes
    lock_timeout: 600


- name: Download and dearmor Caddy GPG key (Cloudsmith recommended method)
  shell: |
    curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' \
      | gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
  args:
    creates: /usr/share/keyrings/caddy-stable-archive-keyring.gpg


- name: Add Caddy repository (Cloudsmith recommended method)
  shell: |
    curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' \
      | tee /etc/apt/sources.list.d/caddy-stable.list
  args:
    creates: /etc/apt/sources.list.d/caddy-stable.list


- name: Fix permissions for key and repo file
  file:
    path: "{{ item }}"
    mode: '0644'
  loop:
    - /usr/share/keyrings/caddy-stable-archive-keyring.gpg
    - /etc/apt/sources.list.d/caddy-stable.list


- name: Update apt cache after adding Caddy repo
  apt:
    update_cache: yes

- name: Install Caddy
  apt:
    name: caddy
    state: present

- name: Hold caddy package
  dpkg_selections:
    name: caddy
    selection: hold

- name: Stop caddy before replacing binary
  service:
    name: caddy
    state: stopped

- name: Remove existing /usr/bin/caddy
  file:
    path: /usr/bin/caddy
    state: absent

- name: Download Caddy binary with OVH DNS plugin
  get_url:
    url: "https://caddyserver.com/api/download?os=linux&arch=amd64&p=github.com/caddy-dns/ovh"
    dest: /usr/bin/caddy
    mode: '0755'
    force: yes

## TODO: Handler
- name: Restart caddy
  service:
    name: caddy
    state: restarted