all:
  children:
    proxy:
      hosts:
        treafik:
          ansible_host: 192.168.100.199
          ansible_user: root

    # dns:
    #   hosts:
    #     adguard:
    #       ansible_host: 192.168.100.39
    #       ansible_user: root