all:
  children:
    proxy:
      hosts:
        caddy:
          ansible_host: 192.168.100.199
          ansible_user: root
        docker01:
          ansible_host: 192.168.100.40
          ansible_user: ubuntu

    # dns:
    #   hosts:
    #     adguard:
    #       ansible_host: 192.168.100.39
    #       ansible_user: root