version: "3.9"

services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${APPDATA_PATH}/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    networks:
      - arrnet

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:libtorrentv1
    container_name: qbittorrent
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - ${APPDATA_PATH}/qbittorrent:/config
      - ${DATA_PATH}/torrents:/data/torrents
    ports:
      - 8080:8080
      - 6881:6881/tcp
      - 6881:6881/udp
    restart: unless-stopped
    networks:
      - arrnet

  radarr:
    image: ghcr.io/hotio/radarr:latest
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${APPDATA_PATH}/radarr:/config
      - ${DATA_PATH}:/data
    ports:
      - 7878:7878
    restart: unless-stopped
    networks:
      - arrnet

  sonarr:
    image: ghcr.io/hotio/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${APPDATA_PATH}/sonarr:/config
      - ${DATA_PATH}:/data
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      - arrnet

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${APPDATA_PATH}/bazarr:/config
      - ${DATA_PATH}:/data
    ports:
      - 6767:6767
    restart: unless-stopped
    networks:
      - arrnet

  flaresolverr:
    image: flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - TZ=${TZ}
      - LOG_LEVEL=info
    ports:
      - 8191:8191
    restart: unless-stopped
    networks:
      - arrnet

networks:
  arrnet:
    name: arrnet
    driver: bridge
