name: Refresh Caddy

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'caddy/**'
      - 'ansible/roles/setup_caddy/**'
      - '.github/workflows/caddy-refresh.yml'

jobs:
  refresh-caddy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v6

      - name: Create vault password file
        working-directory: ./ansible
        run: echo "${{ secrets.ANSIBLE_VAULT_PASSWORD }}" > vault_pass.txt

      - name: Refresh Caddy configuration and restart service
        working-directory: ./ansible
        run: |

          ansible-playbook -i inventory.yml playbooks/caddy-refresh.yml -v --vault-password-file vault_pass.txt
