name: Refresh Docker Compose Stack

on:
  push:
    branches:
      - main
    paths:
      - 'ansible/playbooks/docker-refresh.yml'
      - 'apps/**'
  workflow_dispatch:
jobs:
  refresh-docker-compose:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v6

      - name: Create vault password file
        working-directory: ./ansible
        run: echo "${{ secrets.ANSIBLE_VAULT_PASSWORD }}" > vault_pass.txt

      - name: Setup Python virtual environment
        working-directory: ./ansible
        run: |
          python3 -m venv .venv
          . .venv/bin/activate
          python -m pip install --upgrade pip
          pip install ansible-core docker
        shell: bash

      - name: Refresh Docker Compose stack on docker01
        working-directory: ./ansible
        run: |
          . .venv/bin/activate
          ansible-playbook -i inventory.yml playbooks/docker-refresh.yml -v --vault-password-file vault_pass.txt
        shell: bash